# Per-item reminders: bell on habits, steps, day goals and goals; sheet edits save at once and reach the alarm list.
import asyncio,re
from playwright.async_api import async_playwright
ok=lambda c,m:print(('PASS ' if c else 'FAIL ')+m)
MOCK=re.search(r'MOCK=r"""(.*?)"""',open('/home/claude/scripts/t30.py').read(),re.S).group(1)
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch();ctx=await b.new_context(viewport={'width':390,'height':844});await ctx.add_init_script(MOCK)
    pg=await ctx.new_page();errs=[];pg.on('pageerror',lambda e:errs.append(str(e)))
    await pg.goto('http://localhost:8765/index.html');await pg.wait_for_timeout(600)
    await pg.fill('input[name=name]','M');await pg.click('button[value=demo]');await pg.wait_for_timeout(700)
    await pg.evaluate("S.settings.tourOffered=true;document.querySelector('.tprompt')?.remove()")
    hid=await pg.evaluate("(()=>{const h=S.habits.find(h=>h.kind==='build'&&h.status==='active');h.remind=false;h.time='';h.part='evening';return h.id})()")
    await pg.evaluate(f"go('habits')");await pg.wait_for_timeout(500)
    ok(await pg.evaluate("document.querySelectorAll('.hrow .bell').length>0"),'habit rows show a bell')
    await pg.evaluate(f"go('habit/{hid}')");await pg.wait_for_timeout(500)
    await pg.click('.crumb .bell');await pg.wait_for_timeout(300)
    ok(await pg.evaluate("!!document.querySelector('#remBody')"),'bell opens the reminder sheet')
    await pg.click('#remBody .rm-sw');await pg.wait_for_timeout(200)
    r=await pg.evaluate(f"({{on:H('{hid}').remind,t:H('{hid}').time}})");ok(r['on'] and r['t']=='19:00','turning it on defaults to the habit’s part of day (evening 7 PM)')
    await pg.click('#remBody [data-f=again][data-v="60"]');await pg.click('#remBody [data-f=time2][data-v="12:30"]');await pg.wait_for_timeout(200)
    await pg.screenshot(path='/home/claude/scripts/x-rem-habit.png')
    L=await pg.evaluate(f"window.__sched.filter(x=>x.hid==='{hid}').map(x=>x.body.slice(0,12)+'@'+new Date(x.at).getHours()+':'+new Date(x.at).getMinutes())");print(L[:6])
    ok(any('@12:30' in x for x in L) and any('@20:0' in x for x in L) and any('@19:0' in x for x in L),'main, second and nudge reminders scheduled')
    ok(await pg.evaluate("document.querySelector('.rm-next b').textContent.startsWith('Next:')"),'sheet previews the next reminder')
    await pg.evaluate("closeSheet()")
    # step
    g=await pg.evaluate("(()=>{const g=S.goals.find(g=>g.status==='active'&&g.steps.some(s=>!s.done&&s.due));const s=g.steps.find(s=>!s.done&&s.due);s.remind='';s.time='10:00';return{g:g.id,s:s.id}})()")
    await pg.evaluate(f"go('goal/{g['g']}')");await pg.wait_for_timeout(500)
    await pg.evaluate(f"ACT.remEdit({{k:'step',g:'{g['g']}',s:'{g['s']}'}})");await pg.wait_for_timeout(200)
    await pg.click('#remBody .rm-sw');await pg.click('#remBody [data-f=remind][data-v="30"]');await pg.wait_for_timeout(200)
    st=await pg.evaluate(f"(()=>{{const s=G('{g['g']}').steps.find(x=>x.id==='{g['s']}');return{{r:s.remind,at:reminderAt(s)}}}})()");ok(st['r']=='30','step reminder set to 30 min before')
    await pg.click('#remBody [data-f=remind][data-v="c"]');await pg.wait_for_timeout(150)
    await pg.fill('#remBody [data-rm=remTime]','06:45');await pg.dispatch_event('#remBody [data-rm=remTime]','change');await pg.wait_for_timeout(150)
    ok(await pg.evaluate(f"new Date(reminderAt(G('{g['g']}').steps.find(x=>x.id==='{g['s']}'))).getHours()===6"),'custom date and time works')
    await pg.evaluate("closeSheet()")
    # goal sheet
    await pg.evaluate(f"G('{g['g']}').targetDate=addDays(10);render(false)");await pg.click('.crumb .bell');await pg.wait_for_timeout(300)
    await pg.click('#remBody [data-f=checkin][data-v=weekly]');await pg.click('#remBody [data-f=remTarget][data-v="7"]');await pg.wait_for_timeout(200)
    ks=await pg.evaluate(f"window.__sched.filter(x=>x.g==='{g['g']}').map(x=>x.title.slice(0,8))");print(ks)
    ok(any(x.startswith('Target') for x in ks) and any(x.startswith('Check in') for x in ks),'goal check-in and target-date reminders scheduled')
    ok(await pg.evaluate("document.querySelectorAll('#remBody .rm-st .bell').length>0"),'goal sheet lists steps with their own bells')
    await pg.screenshot(path='/home/claude/scripts/x-rem-goal.png')
    await pg.evaluate("closeSheet()")
    # day goal
    did=await pg.evaluate("(()=>{const x=S.days.find(x=>x.date===ymd()&&!x.done);x.time='23:30';delete x.remind;return x.id})()");await pg.evaluate("go('today')");await pg.wait_for_timeout(400)
    ok(await pg.evaluate("document.querySelectorAll('.li .bell').length>0"),'day goals show a bell')
    await pg.evaluate(f"syncNative()");ok(await pg.evaluate(f"window.__sched.some(x=>x.id==='{did}')"),'day goal with a time reminds at that time by default')
    await pg.evaluate(f"ACT.remEdit({{k:'day',id:'{did}'}})");await pg.click('#remBody [data-f=remind][data-v="15"]');await pg.wait_for_timeout(150)
    ok(await pg.evaluate(f"new Date(window.__sched.find(x=>x.id==='{did}').at).getMinutes()===15"),'day goal 15 min before')
    print('errors',errs);await b.close()
asyncio.run(main())
