# 2.0.5: engine hooks used by the native Settings and Ask pages
import asyncio,json
from playwright.async_api import async_playwright
MOCK="""window.__store='';window.PlotlineNative={shellMode(){return true},storeGet(){return window.__store},storeSet(j){window.__store=j},unlocked(){},widget(){},schedule(){},widgetQueue(){return '[]'},importText(){return window.__imp||''},voiceState(){return '{}'},copy(){},classicOn(){return window.__cl===undefined?true:window.__cl},nroute(r){window.__nr=r},ntoast(m,u){window.__nt=m},nconfirm(t,m,o,d){window.__nc=[t,m,o,d]},nneedUi(){window.__nu=(window.__nu||0)+1},nsheet(k,j){window.__ns=[k,j]}};"""
async def main():
  fails=0
  def ok(n,v):
    nonlocal fails;print(('PASS ' if v else 'FAIL ')+n);fails+=0 if v else 1
  async with async_playwright() as p:
    b=await p.chromium.launch();ctx=await b.new_context(viewport={'width':390,'height':800})
    pg=await ctx.new_page();errs=[];pg.on('pageerror',lambda e:errs.append(str(e)))
    await pg.add_init_script(MOCK)
    await pg.goto('http://localhost:8765/index.html');await pg.wait_for_timeout(900)
    await pg.fill('input[name=name]','M');await pg.click('button[value=demo]');await pg.wait_for_timeout(1200)
    j=json.loads(await pg.evaluate("window.__nsub()"))
    ok('__nsub has auto/share/voice/lock',all(k in j for k in ['auto','share','voice','lock','msg','on','demo']))
    k=json.loads(await pg.evaluate("window.__nask(false)"))
    ok('__nask basics',('err' not in k) and 'lab' in k and k['has']==False and len(k['sugs'])>0 and isinstance(k['stats'],list))
    await pg.evaluate("window.__nasksend('what did I do this week?')");await pg.wait_for_timeout(2500)
    k=json.loads(await pg.evaluate("window.__nask(false)"))
    ok('__nask after send has a turn',k['has'] and len(k['turns'])==1 and k['turns'][0]['q'].startswith('what did'))
    # theme change from native store is applied by the engine
    await pg.evaluate("""(()=>{const d=JSON.parse(window.__store);d.settings.theme='paper';window.__store=JSON.stringify(d);window.__nativeChanged()})()""");await pg.wait_for_timeout(500)
    ok('native theme change applied',await pg.evaluate("document.documentElement.dataset.theme==='paper'"))
    # import via native text
    bk=json.dumps({'app':'plotline','version':2,'data':{'goals':[{'id':'zz1','title':'Imported goal','area':'health','steps':[],'status':'active','priority':2,'horizon':'month','createdAt':1,'u':1}]}})
    await pg.evaluate("window.__imp="+json.dumps(bk));await pg.evaluate("ACT.nImport({k:'backup'})");await pg.wait_for_timeout(600)
    ok('nImport opens the restore confirm',await pg.evaluate("document.querySelector('#sheet').classList.contains('on')&&/Restore this backup/.test(document.querySelector('#sheet').textContent)"))
    y=json.loads(await pg.evaluate("window.__nyear(0)"))
    ok('__nyear data',all(k in y for k in ['y','done','steps','checks','M','best','notes','qs','active','chs']) and len(y['M'])==12)
    hv=json.loads(await pg.evaluate("window.__nhv()"))
    ok('__nhv lanes',len(hv['lanes'])>0 and all(len(l['st'])==hv['tn']-hv['a']+1 for l in hv['lanes']))
    au=json.loads(await pg.evaluate("window.__nauto()"))
    ok('__nauto shape',all(k in au for k in ['st','places','rules']))
    shd=json.loads(await pg.evaluate("window.__nshare()"))
    ok('__nshare shape',all(k in shd for k in ['ok','sync','on','inv','on_','old']))
    await pg.evaluate("window.__naiset('I want to run a race','','garbage')")
    await pg.evaluate("ACT.parseAI()")
    na=json.loads(await pg.evaluate("window.__nai()"))
    ok('__nai state',('err' not in na) and na['text'].startswith('I want') and len(na['errs'])>0 and not na['has'] and len(na['spec'])>100)
    ok('__naiprompt',len(await pg.evaluate("window.__naiprompt('new')"))>100)
    n0=await pg.evaluate("S.goals.length")
    tb=await pg.evaluate("window.__ntourBegin()")
    tj=json.loads(tb) if tb else {}
    ok('__ntourBegin demo data',len(tj.get('goals',[]))>2 and len(tj.get('habits',[]))>2 and not tj['settings']['sync'].get('on'))
    await pg.evaluate("window.__ntourEnd()")
    ok('__ntourEnd restores',await pg.evaluate("!TOURING&&S.goals.length==%d"%n0))
    wk=json.loads(await pg.evaluate("window.__nweek()"))
    ok('__nweek',all(k in wk for k in ['a','b','done','late','ahead','habits','top']))
    ne=await pg.evaluate("S.entries.length");await pg.evaluate("window.__nweeksave('good','','next')")
    ok('__nweeksave adds a note',await pg.evaluate("S.entries.length")==ne+1)
    ni=json.loads(await pg.evaluate("window.__nins()"))
    ok('__nins',ni['s']['engine'] in ('local','api','copy') and len(ni['llms'])>0 and len(ni['api'])==3)
    await pg.evaluate("window.__ninsset('engine','copy')")
    ok('__ninsset engine',await pg.evaluate("insSet().engine==='copy'"))
    ok('__nabout',len(await pg.evaluate("window.__nabout()"))>20)
    await pg.evaluate("window.__nshprep('goal',S.goals[0].id,'')");await pg.wait_for_timeout(300)
    sj=json.loads(await pg.evaluate("window.__nshGet()") or '{}')
    ok('__nshprep reports (needs sync here)',sj.get('sync')==1 or sj.get('ok')==1 or 'err' in sj)
    hid=await pg.evaluate("S.habits[0].id")
    rn=json.loads(await pg.evaluate("window.__nrem('habit','%s','','')"%hid))
    ok('__nrem habit',isinstance(rn['next'],list) and isinstance(rn['ft'],str))
    ok('__nprompt',len(await pg.evaluate("window.__nprompt()"))>10)
    await pg.evaluate("(()=>{const g=S.goals[0];g.steps.push({id:'sx1',title:'T',due:ymd(),time:'',remind:'0',done:false,note:''});})()")
    ic=json.loads(await pg.evaluate("window.__nics('icsGoal',S.goals[0].id,'')"))
    ok('__nics icsGoal returns a calendar',ic.get('text','').startswith('BEGIN:VCALENDAR') and ic['name'].endswith('.ics'))
    ia=json.loads(await pg.evaluate("window.__nics('icsAll','','')"))
    ok('__nics icsAll',ia.get('text','').count('BEGIN:VEVENT')>=1)
    isx=json.loads(await pg.evaluate("window.__nics('icsStep',S.goals[0].id,'sx1')"))
    ok('__nics icsStep',isx.get('name')=='plotline-step.ics' and 'SUMMARY:T' in isx['text'])
    await pg.evaluate("S.settings.timer={g:S.goals[0].id,s:'sx1',end:1,m:5}")
    ok('__ntimerfin logs focus',await pg.evaluate("window.__ntimerfin()")=='1' and await pg.evaluate("S.goals[0].steps.find(x=>x.id==='sx1').focus")==5)
    ok('download restored after hook',await pg.evaluate("typeof download==='function'&&download.toString().includes('NATIVE')"))
    eid=await pg.evaluate("(S.entries.find(e=>e.type==='note')||S.entries[0]).id")
    ne=json.loads(await pg.evaluate("window.__nentry('%s')"%eid))
    ok('__nentry',('err' not in ne) and ne['title'] and ne['head'])
    sc=json.loads(await pg.evaluate("window.__nscope()"))
    ok('__nscope',isinstance(sc['goals'],list) and 'win' in sc)
    rx=json.loads(await pg.evaluate("window.__nshrx()"))
    ok('__nshrx',rx['max']==50 and len(rx['emo'])==6 and len(rx['quick'])>0)
    ok('__nshhow',len(await pg.evaluate("window.__nshhow()"))>100)
    ok('__nshtoday off',await pg.evaluate("window.__nshtoday()")=='')
    av=json.loads(await pg.evaluate("window.__nactv()"))
    ok('__nactv',all(k in av for k in ['ok','hc','inside','work','top','wk']))
    ok('__ndyreacts',isinstance(json.loads(await pg.evaluate("window.__ndyreacts(ymd())")),list))
    sp=await pg.evaluate("window.__nstudiopage()")
    ok('__nstudiopage',sp.startswith('<!doctype html>') and 'id="studio"' in sp and 'function catPlan' in sp and 'nHidden' not in sp.split('<script>')[-1][:2000])
    spp=json.loads(await pg.evaluate("window.__nstudioparts()"))
    ok('__nstudioparts',all(k in spp for k in ['hello','notes','tray','book']))
    # hidden mode: actions run without the web layer
    await pg.evaluate("window.__cl=false")
    g0=await pg.evaluate("S.goals.length")
    await pg.evaluate("window.__nrun('dupGoal',{id:S.goals[0].id})");await pg.wait_for_timeout(300)
    ok('__nrun dupGoal routes natively',await pg.evaluate("S.goals.length")==g0+1 and (await pg.evaluate("window.__nr||''")).startswith('goal/'))
    ok('toast forwarded',(await pg.evaluate("window.__nt||''")).startswith('Duplicated'))
    await pg.evaluate("window.__nrun('demoRemove',{})");await pg.wait_for_timeout(200)
    nc=await pg.evaluate("window.__nc||null")
    ok('askConfirm bridged',nc is not None and 'sample' in nc[0].lower() and not await pg.evaluate("$('#sheet').classList.contains('on')"))
    await pg.evaluate("window.__nconfYes()");await pg.wait_for_timeout(300)
    ok('confirm runs the action',await pg.evaluate("demoCount()")==0)
    await pg.evaluate("window.__nu=0;window.__nrun('shHow',{})");await pg.wait_for_timeout(600)
    ok('unported web sheet brings the web layer',await pg.evaluate("window.__nu")>=1)
    await pg.evaluate("closeSheet()");await pg.wait_for_timeout(400)
    await pg.evaluate("welcome();setupFlow()");await pg.wait_for_timeout(200)
    ok('web welcome/setup stay off',not await pg.evaluate("$('#sheet').classList.contains('on')"))
    await pg.evaluate("acctChoice('x@y.com')")
    ok('acctChoice native',await pg.evaluate("(window.__ns||[])[0]")=='acct')
    await pg.evaluate("S.settings.timer={g:S.goals[0].id,s:'sx1',end:1,m:5};finishTimer()")
    ok('finishTimer left to native',await pg.evaluate("!!S.settings.timer"))
    await pg.evaluate("S.settings.timer=null;window.__cl=true")
    ok('no page errors',not errs); print(errs[:3])
    await b.close()
  print('FAILS',fails)
asyncio.run(main())
